model = "gpt-5.2-codex"
model_reasoning_effort = "medium"

[features]
web_search_request = true
skills = true

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"

[projects."/Users/georgios/github/dotfiles"]
trust_level = "trusted"

[projects."/Users/georgios"]
trust_level = "untrusted"
